### ISSUE TITLE
SVG Animation on front page logo

### ISSUE THREAD

**Issue by tperale** [Sprtch/website#34]
Use something like this to perform a little animation on the dots.

```css
svg {
  position: absolute; 
  height: 100%; 
  width: 100%; 
  left: 0; 
  top: 0;
}

@keyframes appear {
  0%   { opacity: 0; transform: translateY(-20%); }
  100% { opacity: 1; transform: translateY(0%); }
}

#dot_13, #dot_24 {
  animation: appear 1s 1;
}

#dot_12, #dot_23, #dot_34 {
  animation: appear 2s 1;
}

#dot_11, #dot_22, #dot_33 {
  animation: appear 3s 1;
}

#dot_21, #dot_32, #dot_43 {
  animation: appear 4s 1;
}

#dot_31, #dot_42 {
  animation: appear 5s 1;
}
```
